"""empty message

Revision ID: 76a55d3880de
Revises: 
Create Date: 2021-02-21 18:55:04.325582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a55d3880de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('second_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('joined', sa.DateTime(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('blog_title', sa.String(length=255), nullable=False),
    sa.Column('blog_body', sa.String(length=10000), nullable=False),
    sa.Column('posted', sa.DateTime(), nullable=False),
    sa.Column('dropped', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('authored_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authored_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('model_title', sa.String(length=255), nullable=False),
    sa.Column('model_description', sa.String(length=1500), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=False),
    sa.Column('dropped', sa.DateTime(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('modelled_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modelled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('podcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('podcast_title', sa.String(length=255), nullable=False),
    sa.Column('podcast_thumbnail', sa.String(length=255), nullable=False),
    sa.Column('podcast_url', sa.String(length=255), nullable=False),
    sa.Column('listens', sa.Integer(), nullable=False),
    sa.Column('posted', sa.DateTime(), nullable=False),
    sa.Column('dropped', sa.DateTime(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=1500), nullable=False),
    sa.Column('posted', sa.DateTime(), nullable=False),
    sa.Column('comment_modified', sa.DateTime(), nullable=True),
    sa.Column('commented_by', sa.Integer(), nullable=False),
    sa.Column('commented_on_blog', sa.Integer(), nullable=True),
    sa.Column('commented_on_podcast', sa.Integer(), nullable=True),
    sa.Column('commented_on_model', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commented_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['commented_on_blog'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['commented_on_model'], ['models.id'], ),
    sa.ForeignKeyConstraint(['commented_on_podcast'], ['podcasts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('podcasts')
    op.drop_table('models')
    op.drop_table('blogs')
    op.drop_table('users')
    # ### end Alembic commands ###
